ServerName localhost

ProxyRequests Off


# =========================================================
# Admin
# =========================================================

# "/" 있는 경로
ProxyPass \
    "/goodjob/secret-admin-page/" \
    "http://admin-waf:8080/goodjob/secret-admin-page/"

ProxyPassReverse \
    "/goodjob/secret-admin-page/" \
    "http://admin-waf:8080/goodjob/secret-admin-page/"


# "/" 없는 경로
ProxyPass \
    "/goodjob/secret-admin-page" \
    "http://admin-waf:8080/goodjob/secret-admin-page"

ProxyPassReverse \
    "/goodjob/secret-admin-page" \
    "http://admin-waf:8080/goodjob/secret-admin-page"


# =========================================================
# Public Web
# =========================================================

ProxyPass \
    "/" \
    "http://public-web:80/"

ProxyPassReverse \
    "/" \
    "http://public-web:80/"
