ServerName localhost

ProxyRequests Off


# =========================================================
# Anti URL / Directory Scanning
# =========================================================

<IfModule mod_evasive20.c>
    DOSHashTableSize    3097

    # 동일 URI 반복 요청
    DOSPageCount        10
    DOSPageInterval     1

    # 동일 IP의 전체 요청 수
    DOSSiteCount        30
    DOSSiteInterval     1

    # 차단 시간
    DOSBlockingPeriod   60
</IfModule>


# =========================================================
# Admin
# =========================================================

ProxyPass \
    "/goodjob/secret-admin-page/" \
    "http://admin-waf:8080/goodjob/secret-admin-page/"

ProxyPassReverse \
    "/goodjob/secret-admin-page/" \
    "http://admin-waf:8080/goodjob/secret-admin-page/"


ProxyPass \
    "/goodjob/secret-admin-page" \
    "http://admin-waf:8080/goodjob/secret-admin-page"

ProxyPassReverse \
    "/goodjob/secret-admin-page" \
    "http://admin-waf:8080/goodjob/secret-admin-page"


# =========================================================
# Public Web
# =========================================================

ProxyPass \
    "/" \
    "http://public-web:80/"

ProxyPassReverse \
    "/" \
    "http://public-web:80/"
